##What is a Python Library?

A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer. As we don’t need to write the same code again and again for different programs. Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

Heres the link to the complete NumPy Documentation <br>
https://numpy.org/doc/2.0/

##**What is NumPy?**<br>
NumPy is a library of Python that will help in analyzing the data. It is used by individuals who deal with data science. It is a linear algebra library.

**How to install NumPy?**<br>
To install NumPy using pip:


In [3]:
!pip install numpy

ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 242, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 441, in run
    conflicts = self._determine_conflicts(to_install)
  File "/usr/local/lib/python3.10/dist-packages/pip/_i

**What are NumPy Arrays?**<br>
While working with NumPy for data science, mostly we have to deal with NumPy arrays. These arrays are of two types:
1.	Matrices:<br>
Matrices are usually two-dimensional but they can still have either only one row or one column.
2. Vectors:<br>
Vectors on the other hand are strictly one-dimensional.


**How to create NumPy Arrays using lists?**<br>
→ Importing the library



In [4]:
import numpy as np

In [5]:
arr=np.random.rand(3,3)
result = arr + np.array([1, 2, 3])
result

array([[1.44602282, 2.65544747, 3.8243359 ],
       [1.75856698, 2.38559052, 3.98610436],
       [1.79664358, 2.2666974 , 3.55604368]])

→ Creating a list and then converting it into an array of 1 dimension.

In [6]:
list1 = [11,23,34,56]
array1 = np.array(list1)
array1

array([11, 23, 34, 56])

→ Creating a list of lists and converting it into an array of 2 dimensions.

In [7]:
list2 = [[11,22,33],[55,66,77],[88,99,100]]
np.array(list2)

array([[ 11,  22,  33],
       [ 55,  66,  77],
       [ 88,  99, 100]])

As seen above, there are two dimensions i.e rows and columns. The dimension is also indicated with the number of square brackets the values are enclosed in. List1 has one square bracket enclosing the numbers 11, 23, 34, 56 and hence is of one dimension. But in the case of list2, the first number 11 has two square bracket openings before it and hence the list is of two dimensions, 3 rows and 3 columns.

##**How to create NumPy Arrays using built-in methods?**<br>
→ Create using the arange method. The arguments are start, stop and step values. The first value is ‘start’ and goes up to (stop-1) just like the range function.

In [8]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

→ Creating an array of all zeros

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

→ Creating an array of all ones.

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

→ Creating an array where the values are spaced equally in an interval. It takes the arguments: start, stop, number of values

In [12]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

→ Creating an identity matrix.

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

→ Creating an array with random numbers of uniform distribution (0–1).

In [14]:
np.random.rand(3,2)

array([[0.43721688, 0.66207328],
       [0.59904166, 0.21042781],
       [0.43275654, 0.88814157]])

→ Creating an array with random integers using randint() where the arguments to be passed are low, high and size. Low is inclusive and high is exclusive.

In [15]:
np.random.randint(1,50,5)

array([22, 35, 36,  2, 20])

## What are the attributes and methods of NumPy Array?


In [16]:
arr1 = np.arange(10,100,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

→ Reshape method to change the array into a new shape.<br>
Incase while reshaping the matrix is not filled then it will give an error. Make sure that the number of rows multiplied by the number of columns equals the number of elements in the array.

In [17]:
arr1.reshape(3,6)

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

→ Finding the maximum and minimum values in the array.


In [18]:
arr1.max()

95

In [19]:
arr1.min()

10

To know the index at which the max or min value is present, use argmax() or argmin().

In [20]:
arr1.argmax()

17

In [21]:
arr1.argmin()

0

 "shape" method to find the shape of the array.

In [22]:
arr1.shape

(18,)

In [23]:
arr1_reshape=arr1.reshape(3,6)
arr1_reshape.shape

(3, 6)

→ Finding the datatype of the elements in the array.

In [24]:
arr1.dtype

dtype('int64')

## **Indexing and Slicing**
###  **1D Numpy array**

To select(slice) a particular element.

In [25]:
arr1[4]

30

In [26]:
arr1[3:7]

array([25, 30, 35, 40])

To replace(broadcast) particular elements in the array.

In [27]:
arr1[3:7]=50
arr1

array([10, 15, 20, 50, 50, 50, 50, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [28]:
#arr1[:]=100
#arr1

To create a new array with these changes rather than changing the original array, we can create a copy of arr1.

In [29]:
arr1_copy=arr1.copy()
arr1_copy[11:15]=60
arr1_copy

array([10, 15, 20, 50, 50, 50, 50, 45, 50, 55, 60, 60, 60, 60, 60, 85, 90,
       95])

In [30]:
arr1

array([10, 15, 20, 50, 50, 50, 50, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

### 2D Numpy Array

In [31]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing:Two different brackets starting with row values and ending with column values.

In [32]:
arr2[2][2]

9

To get the subpart of a matrix: ":value" will consider all rows/columns before that value row/column(exclusive). "value:" will consider all rows/columns after value row/column(inclusive).

In [33]:
arr2[:1,1:]

array([[2, 3]])

In [34]:
arr2[0:,:1]

array([[1],
       [4],
       [7]])

## How to perform conditional selection using a boolean array?

In [35]:
boolean_arr=arr1>45
boolean_arr

array([False, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

To get the values where True:

In [36]:
arr1[arr1>45]

array([50, 50, 50, 50, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [37]:
arr1[boolean_arr]

array([50, 50, 50, 50, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

## Arithmetic Operations on arrays<br>
Arithmetic operations work element-wise on numpy arrays.

In [38]:
arr1+arr1

array([ 20,  30,  40, 100, 100, 100, 100,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190])

In [39]:
arr1*arr1

array([ 100,  225,  400, 2500, 2500, 2500, 2500, 2025, 2500, 3025, 3600,
       4225, 4900, 5625, 6400, 7225, 8100, 9025])

For matrices, the shapes should match, otherwise we get an error.

In [40]:
arr3=np.array([[9,8,7,6],[4,5,6,9],[2,5,3,5]]) #3x4 matrix
arr4=np.array([[9,8,7],[4,5,6],[2,5,3],[6,9,5]]) #4x3 matrix
arr3*arr4.T #Transposing arr4

array([[81, 32, 14, 36],
       [32, 25, 30, 81],
       [14, 30,  9, 25]])

In [41]:
#arr3*arr4

##**How to perform NumPy array universal functions?**
→ Finding the square root of each element in the array.



In [42]:
np.sqrt(arr3)

array([[3.        , 2.82842712, 2.64575131, 2.44948974],
       [2.        , 2.23606798, 2.44948974, 3.        ],
       [1.41421356, 2.23606798, 1.73205081, 2.23606798]])

→ Finding the exponential of each element in the array.

In [43]:
np.exp(arr3)

array([[8.10308393e+03, 2.98095799e+03, 1.09663316e+03, 4.03428793e+02],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 8.10308393e+03],
       [7.38905610e+00, 1.48413159e+02, 2.00855369e+01, 1.48413159e+02]])

→ Finding the maximum of the array.

In [44]:
arr3.max()

9

→ Trigonometric functions

In [45]:
np.sin(arr3)

array([[ 0.41211849,  0.98935825,  0.6569866 , -0.2794155 ],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.41211849],
       [ 0.90929743, -0.95892427,  0.14112001, -0.95892427]])

→ Logarithmic function

In [46]:
np.log(arr3)

array([[2.19722458, 2.07944154, 1.94591015, 1.79175947],
       [1.38629436, 1.60943791, 1.79175947, 2.19722458],
       [0.69314718, 1.60943791, 1.09861229, 1.60943791]])

##Difference between dot product and multiplication of matrices<br>
multiply() multiplies each value of one matrix to the corresponding value at the same position in the other matrix. Requires both matrices to be of the same shape.<br>
<br>
dot() on the other hand multiplies two matrices where the inner dimension of one should match the outer dimension of the other, which will give a resultant matrix of the remaining two dimensions. Eg a 4x3 matric and a 3x4 matrix, when multiplied, will give a 4x4 matrix.

In [47]:
np.dot(arr3,arr4)

array([[163, 201, 162],
       [122, 168, 121],
       [ 74, 101,  78]])

In [48]:
np.multiply(arr3,arr3)

array([[81, 64, 49, 36],
       [16, 25, 36, 81],
       [ 4, 25,  9, 25]])

##The ravel() function<br>
Helps flatten an array of more than one dimension into a single dimension

In [49]:
arr3

array([[9, 8, 7, 6],
       [4, 5, 6, 9],
       [2, 5, 3, 5]])

In [50]:
arr3.ravel()

array([9, 8, 7, 6, 4, 5, 6, 9, 2, 5, 3, 5])

##reshape(1,-1)
  Does the same job as ravel() but does not decrease the number of dimensions, it just fits all values in a single line.

In [51]:
arr3.reshape(1,-1) #As you can see the number of dimensions is still 2

array([[9, 8, 7, 6, 4, 5, 6, 9, 2, 5, 3, 5]])